RandomWalks:
  lr: 0.001
  opt_betas: [0.9, 0.95]
  batch_size: 500
  tau: 0.7
  gamma: 0.99
  cql_scale: 0.1
  awac_scale: 1
  alpha: 0.1
  steps_for_target_q_sync: 10
  steps_for_eval: 5
  inference_betas: [1]
  n_epochs: 2
  seed: 1000
  n_layers_unfrozen: 0
  two_qs: true
  gptconfig:
    n_embd: 144
    n_layer: 6
    n_head: 1